### PR TITLE
Solid way to identify used interface

### LINKED ISSUE #2: Dual-mode dVPN (windows) - Solid way to identify which physical ethernet adapter is used for internet connection

### PR DESCRIPTION
**Pull request by Guillembonet**
From what I gathered, windows uses a metric index that depends on things like (speed, ethernet or wifi, etc) to determine which interface to used for internet access. I did some testing too and it does seem to work like that.

We could find a WMI equivalent of that (which I wasn't able to find), or use the interface index which will not have conflicts with non-latin symbols. For now, I believe that this implementation is solid when it comes to determining the interface used for internet access, but I think it should be tested in more scenarios too before considering it valid. Also, non-latin symbol issues still remain!

Closes: #2

### CODE REVIEW

**Comment by Zensey** [comment]
InterfaceMetric and Win32_NetworkAdapterConfiguration.IPConnectionMetric is pretty much the same, so WMI could be used. 


PS > Get-WmiObject -Query "select * from Win32_NetworkAdapterConfiguration"| select IPEnabled, Description,IPConnectionMetric|Sort-Object -Property IPConnectionMetric

```
IPEnabled Description                              IPConnectionMetric
--------- -----------                              ------------------
    False Intel(R) Ethernet Connection I219-V
    False Microsoft Wi-Fi Direct Virtual Adapter
    False WAN Miniport (IPv6)
    False WAN Miniport (Network Monitor)
    False Hyper-V Virtual Switch Extension Adapter
    False Hyper-V Virtual Switch Extension Adapter
    False Microsoft Wi-Fi Direct Virtual Adapter
    False Hyper-V Virtual Switch Extension Adapter
    False WAN Miniport (IP)
    False WAN Miniport (IKEv2)
    False WAN Miniport (SSTP)
    False Microsoft Kernel Debug Network Adapter
    False Bluetooth Device (Personal Area Network)
    False WAN Miniport (PPPOE)
    False WAN Miniport (PPTP)
    False WAN Miniport (L2TP)
     True Hyper-V Virtual Ethernet Adapter #2      15
     True Hyper-V Virtual Ethernet Adapter         15
     True Intel(R) Dual Band Wireless-AC 8260      50
```


PS > Get-NetIpInterface

```
ifIndex InterfaceAlias                  AddressFamily NlMtu(Bytes) InterfaceMetric Dhcp     ConnectionState PolicyStore
------- --------------                  ------------- ------------ --------------- ----     --------------- -----------
51      vEthernet (WSL)                 IPv4                  1500              15 Disabled Connected       ActiveStore
35      vEthernet (Default Switch)      IPv4                  1500              15 Disabled Connected       ActiveStore
3       Подключение по локальной сет... IPv4                  1500              25 Enabled  Disconnected    ActiveStore
4       Подключение по локальной сет... IPv4                  1500              25 Enabled  Disconnected    ActiveStore
15      Беспроводная сеть_              IPv4                  1500              50 Enabled  Connected       ActiveStore
1       Loopback Pseudo-Interface 1     IPv4            4294967295              75 Disabled Connected       ActiveStore
```

**Comment by Zensey** [comment]
No, InterfaceMetric is a bit different.
However there's some correlation

**Comment by Guillembonet** [comment]
> No, InterfaceMetric is a bit different. However there's some correlation.
> 
> > -InterfaceMetric
> > Specifies an array of metrics of IP interfaces. When routes are chosen, the overall metric used to determine the preference is the sum of the route metric and the interface metric. Typically, the interface metric gives preference to a particular interface, such as using wired if both wired and wireless are available.

So is there a way of identifying accurately?

**Comment by Zensey** [comment]
> > No, InterfaceMetric is a bit different. However there's some correlation.
> > > -InterfaceMetric
> > > Specifies an array of metrics of IP interfaces. When routes are chosen, the overall metric used to determine the preference is the sum of the route metric and the interface metric. Typically, the interface metric gives preference to a particular interface, such as using wired if both wired and wireless are available.
> 
> So is there a way of identifying accurately?

Yes
It turnes out that InterfaceMetric from  Get-NetIpInterface, IPConnectionMetric and route metric from `route -p` have the same values.

**Comment by Zensey** [comment]
This approach is not so easy if you want it to work correctly in all cases.
If there is already a virtual switch and some net adapters being used as external ports then you get something like this:
```
 
ifIndex InterfaceAlias                  AddressFamily NlMtu(Bytes) InterfaceMetric Dhcp     ConnectionState PolicyStore
------- --------------                  ------------- ------------ --------------- ----     --------------- -----------
53      vEthernet (Myst Bridge Switch)  IPv6                  1500              75 Disabled Disconnected    ActiveStore
51      vEthernet (WSL)                 IPv6                  1500              15 Enabled  Connected       ActiveStore
28      vEthernet (Default Switch)      IPv6                  1500              15 Enabled  Connected       ActiveStore
9       Сетевое подключение Bluetooth   IPv6                  1500              65 Disabled Disconnected    ActiveStore
3       Подключение по локальной сет... IPv6                  1500              25 Enabled  Disconnected    ActiveStore
4       Подключение по локальной сет... IPv6                  1500              25 Disabled Disconnected    ActiveStore
14      Беспроводная сеть_              IPv6                  1500              55 Enabled  Connected       ActiveStore
1       Loopback Pseudo-Interface 1     IPv6            4294967295              75 Disabled Connected       ActiveStore
53      vEthernet (Myst Bridge Switch)  IPv4                  1500              75 Enabled  Disconnected    ActiveStore
51      vEthernet (WSL)                 IPv4                  1500              15 Disabled Connected       ActiveStore
28      vEthernet (Default Switch)      IPv4                  1500              15 Disabled Connected       ActiveStore
9       Сетевое подключение Bluetooth   IPv4                  1500              65 Enabled  Disconnected    ActiveStore
3       Подключение по локальной сет... IPv4                  1500              25 Disabled Disconnected    ActiveStore
4       Подключение по локальной сет... IPv4                  1500              25 Enabled  Disconnected    ActiveStore
14      Беспроводная сеть_              IPv4                  1500              55 Enabled  Connected       ActiveStore
1       Loopback Pseudo-Interface 1     IPv4            4294967295              75 Disabled Connected       ActiveStore
```

```

ifIndex InterfaceAlias                  AddressFamily NlMtu(Bytes) InterfaceMetric Dhcp     ConnectionState PolicyStore
------- --------------                  ------------- ------------ --------------- ----     --------------- -----------
57      vEthernet (Myst Bridge Switch)  IPv6                  1500              45 Enabled  Connected       ActiveStore
51      vEthernet (WSL)                 IPv6                  1500              15 Enabled  Connected       ActiveStore
28      vEthernet (Default Switch)      IPv6                  1500              15 Enabled  Connected       ActiveStore
9       Сетевое подключение Bluetooth   IPv6                  1500              65 Disabled Disconnected    ActiveStore
3       Подключение по локальной сет... IPv6                  1500              25 Enabled  Disconnected    ActiveStore
4       Подключение по локальной сет... IPv6                  1500              25 Disabled Disconnected    ActiveStore
15      Ethernet                        IPv6                  1500               5 Enabled  Disconnected    ActiveStore
1       Loopback Pseudo-Interface 1     IPv6            4294967295              75 Disabled Connected       ActiveStore
57      vEthernet (Myst Bridge Switch)  IPv4                  1500              45 Enabled  Connected       ActiveStore
51      vEthernet (WSL)                 IPv4                  1500              15 Disabled Connected       ActiveStore
28      vEthernet (Default Switch)      IPv4                  1500              15 Disabled Connected       ActiveStore
9       Сетевое подключение Bluetooth   IPv4                  1500              65 Enabled  Disconnected    ActiveStore
3       Подключение по локальной сет... IPv4                  1500              25 Disabled Disconnected    ActiveStore
4       Подключение по локальной сет... IPv4                  1500              25 Enabled  Disconnected    ActiveStore
15      Ethernet                        IPv4                  1500               5 Enabled  Disconnected    ActiveStore
1       Loopback Pseudo-Interface 1     IPv4            4294967295              75 Disabled Connected       ActiveStore
```

Physical adapters are getting replaced by virtual and you dont see an original adapter.

**Pull request closed without merging**
